# Generated by Django 5.1b1 on 2024-07-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tokenmodel_isverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenmodel',
            name='user',
            field=models.EmailField(max_length=254),
        ),
    ]
